---

local:
  hosts:
    localhost ansible_connection=local
lg_routers:
  hosts:
    rviews.kanren.net
arctic_switches:
  hosts:
    arctic_sw01:
      ansible_host: 10.1.10.100
    weddell-sw02:
      ansible_host: 10.1.10.40
